"""Human-in-the-loop review gate for the AutoVisionCut pipeline.

Generates human-readable review artifacts from cut_list.json, supports
CSV export for external editing, and blocks assembly until an approval
file is present.
"""

import csv
import json
import os
import time
from pathlib import Path
from typing import Any

from autovideo.logging_setup import get_module_logger

logger = get_module_logger(__name__)

REVIEW_MD_FILENAME = "review.md"
REVIEW_CSV_FILENAME = "cut_list_review.csv"
APPROVED_CUTLIST_FILENAME = "cut_list.approved.json"
OVERRIDES_FILENAME = "overrides.json"

TIME_SAVED_HEADER = "cut_list will remove"


def _load_cut_list(cut_list_path: str) -> dict[str, Any]:
    with open(cut_list_path, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_review_md(cut_list: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("# Cut/Keep Review — Human Review Gate\n")
    decisions = cut_list.get("decisions", [])
    stats = cut_list.get("stats", {})

    lines.append(f"- **Total segments:** {stats.get('total_segments', '?')}")
    lines.append(f"- **Kept:** {stats.get('total_kept', '?')}")
    lines.append(f"- **Cut:** {stats.get('total_cut', '?')}")
    lines.append(f"- **Time saved:** {stats.get('time_saved_seconds', 0):.1f}s\n")

    lines.append("| # | Timestamp | Duration | Decision | Confidence | Tag | Reason |")
    lines.append("|---|--------|--------|--------|--------|--------|--------|")
    for d in decisions:
        seg_id = d.get("id", "?")
        start = d.get("_start", d.get("start", 0))
        end = d.get("_end", d.get("end", 1))
        ts = f"{float(start):.1f}s-{float(end):.1f}s"
        dur = f"{float(end) - float(start):.1f}s"
        decision = d.get("decision", "?")
        conf = f"{d.get('confidence', 0):.0%}"
        tag = d.get("tag", "")
        reason = d.get("reason", "")
        lines.append(f"| {seg_id} | {ts} | {dur} | {decision} | {conf} | {tag} | {reason} |")

    lines.append("\n---\n*Generated by AutoVisionCut Review Gate*")
    return "\n".join(lines)


def export_csv(cut_list: dict[str, Any], output_path: str) -> None:
    decisions = cut_list.get("decisions", [])
    if not decisions:
        logger.info("No decisions to export — CSV not written")
        return

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "start", "end", "decision", "confidence", "tag", "reason", "text"])
        for d in decisions:
            writer.writerow([
                d.get("id", ""),
                d.get("_start", ""),
                d.get("_end", ""),
                d.get("decision", ""),
                d.get("confidence", ""),
                d.get("tag", ""),
                d.get("reason", ""),
                d.get("_text", ""),
            ])

    logger.info("CSV review export written to %s", output_path)


def _enrich_decisions_with_segment_data(
    cut_list: dict[str, Any], segments_path: str
) -> dict[str, Any]:
    decisions = cut_list.get("decisions", [])
    try:
        with open(segments_path, "r", encoding="utf-8") as f:
            segments_data = json.load(f)
        segs = segments_data.get("segments", [])
        seg_map = {s["id"]: s for s in segs if "id" in s}
        for d in decisions:
            sid = d.get("id")
            if sid in seg_map:
                seg = seg_map[sid]
                d["_start"] = seg.get("start", 0)
                d["_end"] = seg.get("end", 0)
                d["_text"] = seg.get("text", "")
    except (FileNotFoundError, json.JSONDecodeError, KeyError) as exc:
        logger.warning("Could not enrich decisions from segments.json: %s", exc)
        for d in decisions:
            d["_start"] = d.get("id", 0)
            d["_end"] = d.get("id", 0) + 1
            d["_text"] = ""
    return cut_list


def _write_artifacts(
    review_md: str,
    csv_path: str,
    cut_list: dict[str, Any],
    output_dir: str,
) -> None:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    md_path = out / REVIEW_MD_FILENAME
    md_path.write_text(review_md, encoding="utf-8")
    logger.info("Review markdown written to %s", md_path)

    export_csv(cut_list, csv_path)


def _check_approval_file(output_dir: str) -> str | None:
    approved_path = os.path.join(output_dir, APPROVED_CUTLIST_FILENAME)
    if os.path.isfile(approved_path) and os.path.getsize(approved_path) > 0:
        return approved_path
    return None


def _check_override_file(output_dir: str) -> str | None:
    override_path = os.path.join(output_dir, REVIEW_CSV_FILENAME)
    if os.path.isfile(override_path) and os.path.getsize(override_path) > 0:
        return override_path
    return None


def _apply_csv_overrides(
    cut_list: dict[str, Any], csv_path: str
) -> dict[str, Any]:
    decisions = cut_list.get("decisions", [])
    dec_map: dict[int, dict[str, Any]] = {}
    for d in decisions:
        sid = d.get("id")
        if isinstance(sid, int):
            dec_map[sid] = d

    overrides_applied = 0
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                sid = int(row.get("id", ""))
            except (ValueError, TypeError):
                continue
            if sid in dec_map:
                new_decision = row.get("decision", "").strip().lower()
                if new_decision in ("keep", "cut") and new_decision != dec_map[sid].get("decision"):
                    dec_map[sid]["decision"] = new_decision
                    dec_map[sid]["reason"] = f"user_override: {row.get('reason', 'edited in CSV')}"
                    overrides_applied += 1

    logger.info("Applied %d user overrides from CSV review", overrides_applied)
    cut_list["decisions"] = sorted(dec_map.values(), key=lambda d: d.get("id", 0))
    cut_list["keep"] = [
        {"start": d["_start"], "end": d["_end"]}
        for d in cut_list["decisions"]
        if d.get("decision") == "keep"
    ]
    # Recompute stats
    kept = sum(1 for d in cut_list["decisions"] if d["decision"] == "keep")
    cut_count = sum(1 for d in cut_list["decisions"] if d["decision"] == "cut")
    kept_duration = sum(
        k["end"] - k["start"]
        for k in cut_list["keep"]
    )
    total_duration = sum(
        d.get("_end", 0) - d.get("_start", 0)
        for d in cut_list["decisions"]
    )
    cut_list["stats"]["total_kept"] = kept
    cut_list["stats"]["total_cut"] = cut_count
    cut_list["stats"]["time_saved_seconds"] = round(max(0.0, total_duration - kept_duration), 3)

    return cut_list


def _persist_overrides(
    cut_list: dict[str, Any], output_dir: str
) -> str | None:
    """Persist human override decisions as labeled examples for criteria learning.

    Writes overrides.json: array of {id, text, decision, original_decision,
    reason} for segments whose decision was changed by the user in the review
    gate. Returns the path or None if no overrides were found.
    """
    overrides = []
    for d in cut_list.get("decisions", []):
        reason = d.get("reason", "")
        if reason.startswith("user_override:"):
            overrides.append({
                "id": d.get("id"),
                "text": d.get("_text", ""),
                "decision": d.get("decision"),
                "original_decision": "keep" if d["decision"] == "cut" else "cut",
                "reason": reason,
            })

    if not overrides:
        return None

    override_path = os.path.join(output_dir, OVERRIDES_FILENAME)
    with open(override_path, "w", encoding="utf-8") as f:
        json.dump(overrides, f, indent=2, ensure_ascii=False)
    logger.info("Persisted %d user overrides to %s", len(overrides), override_path)
    return override_path


def _write_approved_cut_list(cut_list: dict[str, Any], output_dir: str) -> str:
    approved_path = os.path.join(output_dir, APPROVED_CUTLIST_FILENAME)
    os.makedirs(os.path.dirname(approved_path), exist_ok=True)
    with open(approved_path, "w", encoding="utf-8") as f:
        json.dump(cut_list, f, indent=2, ensure_ascii=False)
    logger.info("Approved cut list written to %s", approved_path)
    return approved_path


def run(
    cut_list_path: str,
    segments_path: str,
    output_dir: str,
    approval_required: bool = True,
) -> str | None:
    """Run the review gate.

    Args:
        cut_list_path: Path to cut_list.json from the classifier.
        segments_path: Path to segments.json for enrichment.
        output_dir: Output directory for review artifacts.
        approval_required: If True, halts the pipeline unless an
            approved cut list exists. If False, generates review
            artifacts and passes through.

    Returns:
        The path to the approved cut list if review passes, or None
        if review blocks the pipeline.
    """
    logger.info("Review gate started (cut_list=%s)", cut_list_path)
    start_time = time.monotonic()

    approved_path = _check_approval_file(output_dir)
    if approved_path:
        logger.info("Approved cut list found at %s — review gate passes", approved_path)
        return approved_path

    cut_list = _load_cut_list(cut_list_path)
    cut_list = _enrich_decisions_with_segment_data(cut_list, segments_path)

    csv_path = os.path.join(output_dir, REVIEW_CSV_FILENAME)
    override_path = _check_override_file(output_dir)

    if override_path:
        logger.info("Found edited review CSV at %s — applying overrides", override_path)
        cut_list = _apply_csv_overrides(cut_list, override_path)
        _persist_overrides(cut_list, output_dir)
        approved = _write_approved_cut_list(cut_list, output_dir)
        elapsed = time.monotonic() - start_time
        logger.info("Review gate passed with overrides (elapsed=%.1fs)", elapsed)
        return approved

    review_md = generate_review_md(cut_list)
    _write_artifacts(review_md, csv_path, cut_list, output_dir)

    if approval_required:
        logger.info(
            "=== REVIEW GATE ==="
        )
        logger.info(
            "Review artifacts generated in %s", output_dir
        )
        logger.info(
            "Edit %s to override decisions, or create %s to approve as-is",
            REVIEW_CSV_FILENAME,
            APPROVED_CUTLIST_FILENAME,
        )
        logger.info(
            "Pipeline halting — re-run with approved cut list to continue"
        )
        elapsed = time.monotonic() - start_time
        logger.info("Review gate blocking (elapsed=%.1fs)", elapsed)
        return None

    approved = _write_approved_cut_list(cut_list, output_dir)
    elapsed = time.monotonic() - start_time
    logger.info("Review gate passed (approval not required, elapsed=%.1fs)", elapsed)
    return approved
